# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBIbFuPONz33217jU4UysfaWKvB5-0t5
"""

# Import library yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import hstack

"""## EDA

Tahapan ini dilakukan untuk menilai dataset dan sebagai eksplorasi awal
"""

# Load dataset
df = pd.read_csv('dataset/spotify_songs.csv')
df.head()

# Melihat struktur data
df.info()

# Mengecek jumlah data
df.shape

df.describe()

# Mengecek jumlah missing value
df.isnull().sum()

print(f"Jumlah data lagu unik berdasarkan track_name: {df['track_name'].nunique()}")
print(f"Jumlah data lagu unik berdasarkan track_id: {df['track_id'].nunique()}")

duplicates = df[df.duplicated()]
print(f"Jumlah data duplikat: {len(duplicates)}")

"""## Data Preparation

Tahapan data preparation dilakukan untuk memastikan bahwa data siap digunakan oleh model machine learning dan menghasilkan performa yang optimal
"""

# Menghapus missing value
df.dropna(inplace=True)

df = df.drop_duplicates(subset='track_id').reset_index(drop=True)
print(f"Data setelah di-drop: {df.shape}")

# Menampilkan genre beserta sub genrenya
for genre in df['playlist_genre'].unique():
    print(f"{genre}: {df['playlist_subgenre'][df['playlist_genre'] == genre].unique().tolist()}")

# Hitung rata-rata popularitas per album per artis
album_popularity = df.groupby(
    ['track_artist', 'track_album_id', 'track_album_name'],
    as_index=False
)['track_popularity'].mean()

# Urutkan agar album paling populer per artis ada di atas
top_albums = album_popularity.sort_values(
    ['track_artist', 'track_popularity'],
    ascending=[True, False]
)

# Ambil satu album paling populer untuk tiap artis
top_album_per_artist = top_albums.drop_duplicates('track_artist', keep='first')

# Tampilkan hasilnya
print(top_album_per_artist.head(10))

"""Memilih fitur-fitur penting untuk sistem rekomendasi, termasuk track_name yang nantinya dijadikan index. Tahapan ini perlu karna kita ingin merekomendasikan lagu berdasarkan karakteristiknya."""

def prepare_features(df, text_col='track_name', drop_dupes=True):
    """
    Siapkan data fitur numerik untuk content-based recommendation.

    Parameters:
        df (DataFrame): Dataset asli.
        text_col (str): Kolom teks sebagai nama item (index).
        drop_dupes (bool): Apakah mau buang duplikat berdasarkan nama item.

    Returns:
        DataFrame: Data fitur numerik yang siap dipakai, index = nama item.
        list: Daftar fitur numerik yang digunakan.
    """
    features = ['danceability', 'energy',
                'loudness', 'speechiness', 'acousticness',
                'instrumentalness', 'liveness', 'valence',
                'tempo', 'track_popularity']

    temp = df[[*features, text_col]].copy()

    if drop_dupes:
        temp.drop_duplicates(subset=text_col, inplace=True)

    temp.set_index(text_col, inplace=True)

    return temp, features

# Siapin data fitur numerik
temp, features = prepare_features(df)

"""Normalisasi diperlukan untuk memastikan semua fitur numerik berada di skala yang sama."""

# Normalisasi data numerik
scaler = MinMaxScaler()
scaled_numeric = scaler.fit_transform(temp)

"""## Modeling

Kolom track_name diubah ke numerik dengan algoritma TF-IDF karna model hanya bisa memproses numerik. algoritma ini merupakan teknik dari NLP yang digunakan untuk menghitung bobot kata-kata dalam judul lagu berdasarkan frekuensi kemunculannya, memungkinkan model untuk mengenali kemiripan antar lagu berdasarkan teks judulnya.
"""

# TF-IDF dari track_name
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(temp.index)  # karena track_name udah jadi index

# Gabungin fitur numerik dan TF-IDF
combined_features = hstack([scaled_numeric, tfidf_matrix])

"""cosine similarity digunakan untuk mengukur kemiripan antar lagu berdasarkan vektor hasil tf-idf."""

# Hitung cosine similarity
sim_df = pd.DataFrame(
    cosine_similarity(combined_features),
    index=temp.index,
    columns=temp.index
)

"""## Evaluation

Evaluasi dilakukan secara manual atau sanity check dikarenakan dataset yang digunakan tidak mengandung data user.
Fungsi di bawah akan menampilkan top 10 rekomendasi lagu teratas.
"""

def recommend(track_name, sim_df, top_n=5):
    if track_name not in sim_df.index:
        return f"Lagu '{track_name}' tidak ditemukan."
    similarity_scores = sim_df[track_name].sort_values(ascending=False)
    return similarity_scores.iloc[1:top_n+1]  # skip urutan pertama (karena itu dirinya sendiri)

recommend('Closer', sim_df, top_n=10)